# backend dev environment

# using python image for working with Flask backend
FROM python:3.12-slim

WORKDIR /usr/src/app

# copying requirements txt then installing packages
COPY requirements.txt ./
RUN pip install --upgrade pip && pip install -r requirements.txt